from __future__ import annotations

import hashlib
import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).parents[1]
LINT_PATH = ROOT / "scripts" / "accelerator-lint.py"


def _load_lint():
    spec = importlib.util.spec_from_file_location("diagram_mcp_lint", LINT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _repo(tmp_path: pathlib.Path) -> None:
    contract = (
        "Azure Architecture Diagram Builder MCP\n"
        "list_services validate_architecture render_diagram .mcp.json\n"
        "checksum-bound `.mcp.json`\n"
    )
    for rel in (
        "docs/start/deliver/03-scaffold-from-the-brief.md",
        ".agents/skills/accelerator/SKILL.md",
        "AGENTS.md",
        ".github/copilot-instructions.md",
    ):
        _write(tmp_path / rel, contract)
    _write(
        tmp_path / "scripts/prepare-pages.py",
        'asset_suffixes = {".svg", ".json"}\n',
    )
    _write(
        tmp_path / ".gitattributes",
        "docs/assets/diagrams/*.svg text eol=lf -whitespace\n"
        "docs/assets/diagrams/*.mcp.json text eol=lf\n",
    )

    svg_rel = "docs/assets/diagrams/sales-research-reference.svg"
    provenance_rel = "docs/assets/diagrams/sales-research-reference.mcp.json"
    _write(
        tmp_path / "accelerator.yaml",
        "scenario:\n"
        "  id: sales-research\n"
        "  architecture_diagram:\n"
        f"    path: {svg_rel}\n"
        f"    provenance: {provenance_rel}\n"
        "    generator: azure-architecture-diagram-builder-mcp\n"
        "    version: '1.0.0'\n"
        "    tools: [list_services, validate_architecture, render_diagram]\n",
    )
    svg = (
        "<svg><text>Generated by Azure Architecture Diagram Builder</text>"
        "<text>Azure Architecture Diagram Builder MCP v1.0.0</text></svg>"
    )
    _write(tmp_path / svg_rel, svg)
    provenance = {
        "artifact": {
            "path": "sales-research-reference.svg",
            "sha256": hashlib.sha256(svg.encode()).hexdigest(),
        },
        "generator": {
            "name": "Azure Architecture Diagram Builder MCP",
            "version": "1.0.0",
            "release": "v1.0.0",
            "source_commit": "429a43b1c235bf058945a2fc04c64a4e4ef0b7fd",
            "blog": (
                "https://techcommunity.microsoft.com/blog/"
                "azurearchitectureblog/beyond-the-canvas-the-azure-"
                "architecture-diagram-builder-becomes-agent-ready/4534590"
            ),
            "tools": [
                "list_services",
                "validate_architecture",
                "render_diagram",
            ],
        },
    }
    _write(tmp_path / provenance_rel, f"{json.dumps(provenance)}\n")
    _write(tmp_path / "README.md", f"{svg_rel}\n{provenance_rel}\n")
    for rel in (
        "docs/assets/diagrams/README.md",
        "docs/patterns/architecture/README.md",
    ):
        _write(
            tmp_path / rel,
            "sales-research-reference.svg\nsales-research-reference.mcp.json\n",
        )


def test_mcp_diagram_contract_accepts_checksum_bound_artifact(
    tmp_path: pathlib.Path,
    monkeypatch,
) -> None:
    lint = _load_lint()
    _repo(tmp_path)
    monkeypatch.setattr(lint, "ROOT", tmp_path)

    assert lint.architecture_diagram_mcp_contract(lint.Ctx()) == []


def test_mcp_diagram_contract_rejects_edited_svg(
    tmp_path: pathlib.Path,
    monkeypatch,
) -> None:
    lint = _load_lint()
    _repo(tmp_path)
    monkeypatch.setattr(lint, "ROOT", tmp_path)
    svg = tmp_path / "docs/assets/diagrams/sales-research-reference.svg"
    svg.write_text(f"{svg.read_text(encoding='utf-8')}<!-- edited -->", encoding="utf-8")

    findings = lint.architecture_diagram_mcp_contract(lint.Ctx())

    assert any("checksum does not match" in finding.message for finding in findings)


def test_mcp_diagram_contract_requires_validation_tool(
    tmp_path: pathlib.Path,
    monkeypatch,
) -> None:
    lint = _load_lint()
    _repo(tmp_path)
    monkeypatch.setattr(lint, "ROOT", tmp_path)
    guide = tmp_path / "docs/start/deliver/03-scaffold-from-the-brief.md"
    guide.write_text(
        guide.read_text(encoding="utf-8").replace("validate_architecture", ""),
        encoding="utf-8",
    )

    findings = lint.architecture_diagram_mcp_contract(lint.Ctx())

    assert any("validate_architecture" in finding.message for finding in findings)


def test_mcp_diagram_contract_handles_malformed_generator(
    tmp_path: pathlib.Path,
    monkeypatch,
) -> None:
    lint = _load_lint()
    _repo(tmp_path)
    monkeypatch.setattr(lint, "ROOT", tmp_path)
    provenance = (
        tmp_path / "docs/assets/diagrams/sales-research-reference.mcp.json"
    )
    data = json.loads(provenance.read_text(encoding="utf-8"))
    data["generator"] = "not-an-object"
    provenance.write_text(f"{json.dumps(data)}\n", encoding="utf-8")

    findings = lint.architecture_diagram_mcp_contract(lint.Ctx())

    assert any("generator must be" in finding.message for finding in findings)
