"""Generate or verify the accelerator CLI command reference."""
from __future__ import annotations

import argparse
import contextlib
import io
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "reference" / "accelerator-cli.md"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.accelerator_cli.main import build_parser  # noqa: E402


def render() -> str:
    parser = build_parser()
    with contextlib.redirect_stdout(io.StringIO()) as buffer:
        parser.print_help()
    help_text = buffer.getvalue().rstrip()
    return (
        "# Accelerator CLI reference\n\n"
        "> Generated by `python scripts/generate-cli-docs.py`. Do not edit the "
        "command block manually.\n\n"
        "The CLI emits human-readable output by default and a versioned JSON "
        "contract with `--json`. The wire schema is committed at "
        "`schemas/accelerator-cli-result.schema.json`. Install the local entry "
        "point first with `python -m pip install -e \".[dev]\"`.\n\n"
        "```text\n"
        f"{help_text}\n"
        "```\n\n"
        "## Common workflow\n\n"
        "```powershell\n"
        "accel next\n"
        "accel review\n"
        "accel validate\n"
        "```\n\n"
        "Use `accel <command> --help` for command-specific options.\n"
        "\n## Status and approval model\n\n"
        "| Status | Exit code | Meaning |\n"
        "|---|---:|---|\n"
        "| `complete` / `ready` | 0 | Continue with `next_command` |\n"
        "| `needs_input` | 10 | Collect only the declared missing input |\n"
        "| `approval_required` | 20 | Review proposed actions before applying |\n"
        "| `blocked` | 30 | Resolve the listed issue |\n"
        "| `failed` | 40 | Diagnose the command failure |\n\n"
        "Approval levels are `inspect`, `apply`, `execute`, and `destructive`."
        " Global output flags may appear before or after a subcommand.\n\n"
        "## Document intake and evidence disclosure\n\n"
        "```powershell\n"
        "accel intake add <path> [<path> ...]\n"
        "accel intake list\n"
        "accel intake review <source-id> --limit 50 --offset 0\n"
        "accel intake disclose <source-id> approved_for_model --apply\n"
        "```\n\n"
        "Sources begin as `local_only`. Agent-facing commands cannot return "
        "source text or link extracted evidence to a requirement until the "
        "specific source is approved. Use `--include-text` only after approval. "
        "The private SQLite ledger is gitignored. Supported formats are MD, "
        "TXT, CSV, DOCX, text-layer PDF, PPTX, XLSX, and XLSM. The default "
        "limit is 50 MiB per source (`ACCELERATOR_MAX_SOURCE_BYTES`); macros "
        "are not executed and scanned PDFs require OCR.\n\n"
        "## Requirements traceability\n\n"
        "```powershell\n"
        "accel intake requirement add --category <category> --statement <text> `\n"
        "  --evidence <source-id>:<chunk-id> --apply\n"
        "accel intake requirement decide <requirement-id> approved `\n"
        "  --by <reviewer> --apply\n"
        "accel intake requirement link <requirement-id> `\n"
        "  --type quality_eval `\n"
        "  --target evals/quality/golden_cases.jsonl#<case-id> --apply\n"
        "accel intake requirement export --apply\n"
        "```\n\n"
        "Link types: `implementation`, `quality_eval`, `redteam`, `telemetry`, "
        "`ux`, and `decision`. Exported Markdown contains IDs and sanitized "
        "statements, never private source excerpts.\n\n"
        "## Scaffold and deployment\n\n"
        "```powershell\n"
        "accel design\n"
        "accel scaffold --scenario-id <id> --dry-run\n"
        "accel scaffold --scenario-id <id> --apply\n"
        "accel environment list\n"
        "accel deploy --env <env> --region <region> --dry-run\n"
        "accel deploy --env <env> --region <region> --execute\n"
        "accel deploy --env <env> --region <region> --execute --apply\n"
        "```\n\n"
        "The target comes from `deploy/environments.yaml`; conflicting or "
        "unsupported overrides are rejected. Hosted apply runs both "
        "`azd provision` and `azd deploy` in the nested workspace.\n\n"
        "## Evaluation, UAT, and handover\n\n"
        "```powershell\n"
        "accel evaluate --api-url <url>\n"
        "accel evaluate --api-url <url> --execute\n"
        "accel evaluate --api-url <url> --foundry --execute\n"
        "accel uat report\n"
        "accel uat signoff --sponsor <name> --approver <name> --apply\n"
        "accel handover generate --env <env> --dry-run\n"
        "accel handover generate --env <env> --apply\n"
        "accel handover approve --approver <name> --apply\n"
        "accel operate status\n"
        "```\n\n"
        "Foundry-native evaluation is optional and writes evaluator inputs only "
        "on the explicit `--foundry` path. A generated handover remains a draft "
        "until customer operations approval is recorded.\n\n"
        "## MCP adapter\n\n"
        "Install `.[mcp]` and configure an MCP stdio server whose command is "
        "`accel-mcp`. Read/preview tools are separate from apply and Azure "
        "execution tools so client permission policies remain effective.\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(
                "error: CLI reference is stale; run "
                "`python scripts/generate-cli-docs.py`.",
                file=sys.stderr,
            )
            return 1
        print("CLI reference is current.")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
